# https://habr.com/ru/articles/731110/
# https://hub.docker.com/_/eclipse-mosquitto

version: '3.8'

services:
  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto
    restart: unless-stopped
    ports:
      - "1883:1883/tcp"
    environment:
      - TZ=Europe/Moscow
    volumes:
      - config:/mosquitto/config
      - data:/mosquitto/data

volumes:
  config:
  data: