# https://www.zigbee2mqtt.io/guide/installation/02_docker.html#docker-compose

version: '3.8'

services:
  zigbee2mqtt:
    container_name: zigbee2mqtt
    image: koenkk/zigbee2mqtt
    restart: unless-stopped
    volumes:
      - data:/app/data
      - /run/udev:/run/udev:ro
    ports:
      # Frontend port
      - 3010:8080
    environment:
      - TZ=Europe/Moscow
    devices:
      # Make sure this matched your adapter location
      - /dev/serial/by-id/usb-Silicon_Labs_CP2102_USB_to_UART_Bridge_Controller_0001-if00-port0:/dev/ttyUSB0

volumes:
  data: